config/routes.rb
Rails.application.routes.draw do
  get 'tadpole/edit'

  get 'tadpole/show'

  get 'tadpole/index'

  get 'tadpole/destory'

  get 'pond/edit'

  get '/frogs/:id/tadpoles/new' => 'tadpoles#new'

  get 'pond/show'

  get 'pond/index'

  
  resources :frogs, :ponds, :tadpoles

end

app/models/frog.rb
class Frog < ActiveRecord::Base
 belongs_to :pond
 has_many :tadpoles
end

app/models/pond.rb
class Pond < ActiveRecord::Base
  has_many :frogs
  has_many :tadpoles, through: :frogs
end

app/models/tadpole.rb
class Tadpole < ActiveRecord::Base
  belongs_to :frog

  def evolve
    Frog.create(name: name, color: color, pond: frog.pond)
    destroy
    frog.pond.frogs.find(frog.id).tadpoles.find(id).frog.color
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/frogs_controller.rb
class FrogsController < ApplicationController

  before_action :set_frog, only: [:show, :edit, :update, :destroy]

  def index
    @frogs = Frog.all
  end

  def create
    @frog = Frog.new(frog_params)
    respond_to do |format|
      if @frog.save
        format.html { redirect_to @frog, notice: 'Frog was successfully created.' }
        format.json { render :show, status: :created, location: @frog }
      else
        format.html { render :new }
        format.json { render json: @frog.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @frog = Frog.new
    @ponds = Pond.all
  end

  def show
  end

  def edit
    @ponds = Pond.all
  end

  def update
    @frog = Frog.find(params[:id])
    respond_to do |format|
      if @frog.update(frog_params)
        format.html { redirect_to @frog, notice: 'Frog was successfully updated.' }
        format.json { render :show, status: :ok, location: @frog }
      else
        format.html { render :edit }
        format.json { render json: @frog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @frog.destroy
    respond_to do |format|
      format.html { redirect_to frogs_url, notice: 'Frog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frog
      @frog = Frog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frog_params
      params.require(:frog).permit(:name, :color, :pond_id)
    end
    
end

app/controllers/ponds_controller.rb
class PondsController < ApplicationController
  before_action :set_pond, only: [:show, :edit, :update, :destroy]

  def index
    @ponds = Pond.all
  end

  def create
    @pond = Pond.new(pond_params)
    respond_to do |format|
      if @pond.save
        format.html { redirect_to @pond, notice: 'Pond was successfully created.' }
        format.json { render :show, status: :created, location: @pond }
      else
        format.html { render :new }
        format.json { render json: @pond.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @pond = Pond.new
  end

  def show
  end

  def edit
  end

  def update
    @pond = Pond.find(params[:id])
    respond_to do |format|
      if @pond.update(pond_params)
        format.html { redirect_to @pond, notice: 'Pond was successfully created.' }
        format.json { render :show, status: :created, location: @pond }
      else
        format.html { render :new }
        format.json { render json: @pond.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pond.destroy
    respond_to do |format|
      format.html { redirect_to ponds_url, notice: 'Pond was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pond
      @pond = Pond.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pond_params
      params.require(:pond).permit(:name, :water_type)
    end

end

app/controllers/tadpoles_controller.rb
class TadpolesController < ApplicationController
  before_action :set_tadpole, only: [:show, :edit, :update, :destroy]

  def index
    @tadpoles = Tadpole.all
  end

  def new
    @frog = Frog.find(params[:id])
    @tadpole = Tadpole.new
  end

  def create
    @tadpole = Tadpole.new(tadpole_params)
    respond_to do |format|
      if @tadpole.save
        format.html { redirect_to @tadpole, notice: 'Tadpole was successfully created.' }
        format.json { render :show, status: :created, location: @tadpole }
      else
        format.html { render :new }
        format.json { render json: @tadpole.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @tadpole = Tadpole.find(params[:id])
  end

  def edit
  end

  def update
    respond_to do |format|
      if @tadpole.update(tadpole_params)
        format.html { redirect_to @tadpole, notice: 'Tadpole was successfully updated.' }
        format.json { render :show, status: :ok, location: @tadpole }
      else
        format.html { render :edit }
        format.json { render json: @tadpole.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tadpole.destroy
    respond_to do |format|
      format.html { redirect_to tadpoles_url, notice: 'Tadpole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def evolve
    tadpole = Tadpole.find(params[:id])
    tadpole.evolve
    redirect_to tadpoles_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tadpole
      @tadpole = Tadpole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tadpole_params
      params.require(:tadpole).permit(:name, :color, :frog_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pond_helper.rb
module PondHelper
end

app/helpers/tadpole_helper.rb
module TadpoleHelper
end

app/views/frogs/_form.html.erb
<%= form_for(@frog, url: {action: "create"}, html: {class: "nifty_form"}) do |f|%>
<%= f.text_field(:name) %><br>
<%= f.text_field(:color) %><br>
  Choose your pond, besh!<br>
  <%= f.collection_select(:pond_id, Pond.all, :id, :name) %><br>
  <%= f.submit %>
<% end %>

app/views/frogs/edit.html.erb
<h1>Edit <%= @frog.name %></h1>
<form action="/frogs/<%= @frog.id %>/update" method="post">
  <label for="name">Name</label>
  <input type="text" id="name" name="name" placeholder="<%= @frog.name %>">
  <label for="color">Color</label>
  <input type="text" id="color" name="color" placeholder="<%= @frog.color %>">
  <label for="lives">Lives</label>
  <select id="lives" name="pond_id">
    <% @ponds.each do |pond| %>
      <option value="<%= pond.id %>"><%= pond.name %></option>
    <% end %>
  </select>
  <input type="submit" value="update">
</form><br>
<%= link_to('Cancle', frogs_path) %>

app/views/frogs/index.html.erb
<%= render 'layouts/header' %>

<h1>Frogs</h1>
<% @frogs.each do |frog| %>
  <p><a href="/frogs/<%= frog.id %>"><%= frog.name %></a></p>
<% end %>
<p><a href="/frogs/new">Create a new frog</a></p>

<%= render 'layouts/footer' %>

app/views/frogs/new.html.erb
<h1>Create a new frog</h1>
<%= render "form" %>
<br>
<%= link_to('Cancel', frogs_path) %>

app/views/frogs/show.html.erb
<h1><%= @frog.name %> Frog</h1>
<p>Color: <%= @frog.color %></p>
<p>Lives: <a href="/ponds/<%= @frog.pond.id %>"><%= @frog.pond.name %></a></p>
<% unless @frog.tadpoles.empty? %>
  <h2>Children</h2>
  <ol>
    <% @frog.tadpoles.each do |tadpole| %>
      <li><a href="/tadpoles/<%= tadpole.id %>"><%= tadpole.name %></a></li>
    <% end %>
  </ol><br>
<% end %>
<p><strong><a href="/frogs/<%= @frog.id %>/tadpoles/new">Create new tadpole baby</a></strong></p>
<a href="/frogs">Back</a> | 
<a href="/frogs/<%= @frog.id %>/edit">Edit</a> | 
<%= button_to "Destroy", frog_path, method: :delete %> 

app/views/layouts/_footer.html.erb
</body>
</html>

app/views/layouts/_header.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Pollywog Ranch</title>
    <link rel="stylesheet" href="/css/style.css">
  </head>
  <body>
    <nav>
      <a href="/ponds">Ponds</a> | 
      <a href="/frogs">Frogs</a> | 
      <a href="/tadpoles">Tadpoles</a>
    </nav>

app/views/ponds/_form.html.erb
<%= form_for(@pond) do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :water_type %>
  <%= f.text_field :water_type %><br>

  <%= f.submit %>
<% end %>

app/views/ponds/edit.html.erb
<h1>Edit <%= @pond.name %></h1>
<%= render 'form' %>
<a href="/ponds">Cancel</a>

app/views/ponds/index.html.erb
<%= render 'layouts/header' %>

<h1>Ponds</h1>
<% @ponds.each do |pond| %>
  <p><a href="/ponds/<%= pond.id %>"><%= pond.name %></a></p>
<% end %>
<p><a href="/ponds/new">Create a new pond</a></p>

<%= render 'layouts/footer' %>

app/views/ponds/new.html.erb
<h1>Create a new pond</h1>
<%= render 'form' %>
<a href="/ponds">Cancel</a>

app/views/ponds/show.html.erb
<h1><%= @pond.name %> Pond</h1>
<p>water type: <%= @pond.water_type %></p>
<p>Resident frogs and their tadpoles:</p>
<ol>
  <% @pond.frogs.each do |frog| %>
    <li><a href="/frogs/<%= frog.id %>"><%= frog.name %> frog</a>
      <ol>
        <% frog.tadpoles.each do |tadpole| %>
          <li><a href="/tadpoles/<%= tadpole.id %>"><%= tadpole.name %> tadpole</a></li>
        <% end %>
      </ol>
    </li>
  <% end %>
</ol>
<a href="/ponds">Back</a> | 
<%= link_to "Edit", @pond %> |
<%= link_to "Delete", @pond, method: :delete %>

app/views/tadpoles/_form.html.erb
<%= form_for(@tadpole) do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.hidden_field :color, :value => @frog.color %>
  <%= f.hidden_field :frog_id, :value => @frog.id %>
  <%= f.submit %>
<% end %>

app/views/tadpoles/edit.html.erb
<h1>Edit <%= @tadpole.name %></h1>
<form action="/tadpoles/<%= @tadpole.id %>/update" method="post">
  <label for="name">Name</label>
  <input type="text" id="name" name="name" placeholder="<%= @tadpole.name %>">
  <label for="color">Color</label>
  <input type="text" id="color" name="color" placeholder="<%= @tadpole.color %>">
  <input type="submit" value="update">
</form><br>
<a href="/tadpoles">Cancel</a>

app/views/tadpoles/index.html.erb
<%= render 'layouts/header' %>

<h1>Tadpoles</h1>
<% @tadpoles.each do |tadpole| %>
  <p><a href="/tadpoles/<%= tadpole.id %>"><%= tadpole.name %></a></p>
<% end %>

<%= render 'layouts/footer' %>

app/views/tadpoles/new.html.erb
<h1>Create a new tadpole for <%= @frog.name %></h1>
<%= render 'form' %>
<a href="/tadpoles">Cancel</a>

app/views/tadpoles/show.html.erb
<h1><%= @tadpole.name %> Tadpole</h1>
<p>color: <%= @tadpole.color %></p>
<p>parent: <a href="/frogs/<%= @tadpole.frog.id %>"><%= @tadpole.frog.name %></a></p>
<p>lives: <a href="/ponds/<%= @tadpole.frog.id %>"><%= @tadpole.frog.pond.name %></a></p>
<p><strong><a href="/tadpoles/<%= @tadpole.id %>/evolve">Evolve to frog</a></strong></p>
<a href="/tadpoles">Back</a> | 
<%= link_to "Edit", @tadpole %> |
<%= link_to "Delete", @tadpole, method: :delete %>